/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Graphics;
import java.util.LinkedList;

/**
 *
 * @author JulianCamilo
 */
public class Fondo extends javax.swing.JPanel {

    private boolean detalleMina;
    private LinkedList<String> detalles;
    
    
    /**
     * Creates new form Fondo
     */
    public Fondo() {
        initComponents();
        this.detalleMina=true;
        this.detalles=new LinkedList<>();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        g.drawString("Bienvenido a Minas El Álamo", this.getWidth()/2-70, 20);
        
        
        if(!this.isDetalleMina()){
            detalles.stream().map((detalle) -> detalle.split("-")).forEachOrdered((datos) -> {
                g.drawString(datos[0], Integer.parseInt(datos[1])-80, Integer.parseInt(datos[2])+10);
            });
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the detalleMina
     */
    public boolean isDetalleMina() {
        return detalleMina;
    }

    /**
     * @param detalleMina the detalleMina to set
     */
    public void setDetalleMina(boolean detalleMina) {
        this.detalleMina = detalleMina;
    }

    public static int getABORT() {
        return ABORT;
    }

    public LinkedList getDetalle() {
        return detalles;
    }

    public void setDetalle(LinkedList detalle) {
        this.detalles = detalle;
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
